version: "3.3"
services:
  app:
    build: ./docker/app/
    depends_on:
      - db
    env_file:
      - "variables.env"
    stdin_open: true
    tty: true
    networks:
      - back
  db:
    build: ./docker/db/
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    restart: always
    env_file:
      - "variables.env"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - back
volumes:
  my-db:
networks:
  back:
    name: coingecko_backend
